"""add {{cookiecutter.model_slug_snakecase}} table

Revision ID: 6535654405d4
Revises: 
Create Date: 2021-01-15 10:20:31.976503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6535654405d4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "{{cookiecutter.model_slug_snakecase|replace('_', '')}}",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("{{cookiecutter.model_slug_snakecase|replace('_', '')}}")
    # ### end Alembic commands ###
